spring.application.name=internship-tracker-api
jwt.secret=QE5jUmZValhuMnI1dTh4L0E/RChHK0tiUGRTZ1ZrWXA=
jwt.duration=86400000
spring.datasource.url=jdbc:postgresql://localhost:5433/trackerDB
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect